name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm test

  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.INCOMING_WEBHOOK_URL }}
      with:
        text: slack-incoming-webhook sample
        attachments: |
          [
            {
              "color": "good",
              "author_name": "${{ github.actor }}",
              "author_icon": "http://github.com/${{ github.actor }}.png?size=32",
              "fields": [
                {
                  "title": "Actions URL",
                  "value": "https://github.com/${{ github.repository }}/actions"
                },
                {
                  "title": "Commit message",
                  "value": "${{ env.COMMIT_MESSAGE }}"
                }
              ]
            }
          ]
